package com.thmub.cocobook.model.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.thmub.cocobook.model.bean.BookSearchBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BOOK_SEARCH_BEAN".
*/
public class BookSearchBeanDao extends AbstractDao<BookSearchBean, String> {

    public static final String TABLENAME = "BOOK_SEARCH_BEAN";

    /**
     * Properties of entity BookSearchBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Keyword = new Property(0, String.class, "keyword", true, "KEYWORD");
    }


    public BookSearchBeanDao(DaoConfig config) {
        super(config);
    }
    
    public BookSearchBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BOOK_SEARCH_BEAN\" (" + //
                "\"KEYWORD\" TEXT PRIMARY KEY NOT NULL );"); // 0: keyword
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BOOK_SEARCH_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BookSearchBean entity) {
        stmt.clearBindings();
 
        String keyword = entity.getKeyword();
        if (keyword != null) {
            stmt.bindString(1, keyword);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BookSearchBean entity) {
        stmt.clearBindings();
 
        String keyword = entity.getKeyword();
        if (keyword != null) {
            stmt.bindString(1, keyword);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public BookSearchBean readEntity(Cursor cursor, int offset) {
        BookSearchBean entity = new BookSearchBean( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0) // keyword
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BookSearchBean entity, int offset) {
        entity.setKeyword(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
     }
    
    @Override
    protected final String updateKeyAfterInsert(BookSearchBean entity, long rowId) {
        return entity.getKeyword();
    }
    
    @Override
    public String getKey(BookSearchBean entity) {
        if(entity != null) {
            return entity.getKeyword();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(BookSearchBean entity) {
        return entity.getKeyword() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
